# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-11 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
                ('response_type', models.SmallIntegerField(choices=[(1, 'Radio Select'), (2, 'Text Field'), (3, 'Multiple Choice')])),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='instructor.Roles'),
            preserve_default=False,
        ),
    ]
